blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import ArticleCreateView, ArticleListView, ArticleDetailView, ArticleUpdateView, ArticleDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('create/', ArticleCreateView.as_view(), name='create'),
    path('update/<str:slug>/', ArticleUpdateView.as_view(), name='update'),
    path('delete/<str:slug>/', ArticleDeleteView.as_view(), name='delete'),
    path('', ArticleListView.as_view(), name='list'),
    path('view/<str:slug>/', ArticleDetailView.as_view(), name='view'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from catalog import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models


class Article(models.Model):
    title = models.CharField(max_length=150, verbose_name='заголовок')
    slug = models.CharField(verbose_name='slag')
    text = models.TextField(verbose_name='содержимое')
    preview = models.ImageField(upload_to='previews/', verbose_name='превью', blank=True, null=True)
    created_at = models.DateField(verbose_name='дата создания', auto_now_add=True)
    is_published = models.BooleanField(verbose_name='Опубликовано', default=False)
    view_count = models.IntegerField(verbose_name='Количество просмотров', default='0')

    def __str__(self):
        return f'{self.title}'

    class Meta:
        verbose_name = 'Статья'
        verbose_name_plural = 'Статьи'

blog/views.py
from django.contrib.auth.mixins import UserPassesTestMixin
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView
from pytils.translit import slugify

from blog.models import Article
from blog.utils import EmailThread


class ArticleCreateView(UserPassesTestMixin, CreateView):
    model = Article
    fields = ('title', 'text', 'preview', 'is_published')
    success_url = reverse_lazy('blog:list')

    def form_valid(self, form):
        if form.is_valid():
            new_article = form.save()
            new_article.slug = slugify(new_article.title)
            new_article.save()
        return super().form_valid(form)

    def test_func(self):
        return self.request.user.groups.filter(name="content_manager").exists()

    def handle_no_permission(self):
        return render(request=self.request, template_name='catalog/no_permissions.html')


class ArticleUpdateView(UserPassesTestMixin, UpdateView):
    model = Article
    fields = ('title', 'text', 'preview', 'is_published')

    def form_valid(self, form):
        if form.is_valid():
            new_article = form.save()
            new_article.slug = slugify(new_article.title)
            new_article.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('blog:view', args=[self.kwargs.get('slug')])

    def test_func(self):
        return self.request.user.groups.filter(name="content_manager").exists()

    def handle_no_permission(self):
        return render(request=self.request, template_name='catalog/no_permissions.html')


class ArticleDeleteView(UserPassesTestMixin, DeleteView):
    model = Article
    success_url = reverse_lazy('blog:list')

    def test_func(self):
        return self.request.user.groups.filter(name="content_manager").exists()

    def handle_no_permission(self):
        return render(request=self.request, template_name='catalog/no_permissions.html')


class ArticleListView(ListView):
    model = Article

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(is_published=True)
        return queryset


class ArticleDetailView(DetailView):
    model = Article

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.view_count += 1
        self.object.save()
        if self.object.view_count == 100:
            EmailThread().start()
        return self.object

blog/templates/blog/article_confirm_delete.html
{% extends 'catalog/base.html' %}
{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p><b>Хотите удалить статью <q>{{object.title}}</q>?</b></p>
                        <button type="submit" class="btn btn-danger">Удалить</button>
                        <a href="{% url 'blog:list' %}" class="btn btn-warning">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/article_detail.html
{% extends 'catalog/base.html' %}
{% block content %}
<div class="col-12">
    <div class="row">
        <div class="card" style="width: 100%;">
            {% if object.preview %}
            <img src="{{object.preview.url}}" width="80" height="80" class="card-img-left" alt="...">
            {% endif %}
            <div class="card-body">
                <h5 class="card-title">{{object.title}}</h5>
                <p class="card-text">{{object.text}}</p>
                <div class="card-footer">
                    <p class="card-text">Опубликовано: {{object.created_at}}</p>
                    <p class="card-text">Количество просмотров: {{object.view_count}}</p>
                </div>
            </div>
        </div>
        <div class="mb-3 mt-3" style="text-align: center;">
            <a class="p-2 btn btn-success" href="{% url 'blog:list' %}">Назад</a>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/article_form.html
{% extends 'catalog/base.html' %}
{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6 offset-3">
            <div class="card">
                <div class="card-body">
                    <form action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{form.as_p}}
                        <button type="submit" class="btn btn-success">
                            {% if object %}
                                Сохранить
                            {% else %}
                                Создать
                            {% endif %}
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/article_list.html
{% extends 'catalog/base.html' %}
{% block content %}
<div class="col-12">
    <div class="row justify-content-between">
        {% for object in object_list %}
        <div class="card col-6 p-0" >
            {% if object.preview %}
            <img src="{{object.preview.url}}" width="80" height="80" class="card-img-left" alt="...">
            {% endif %}
            <div class="card-body">
                <h5 class="card-title">{{object.title}}</h5>
                <p class="card-text">{{object.text|truncatechars:100}}</p>
            </div>
            <div class="card-footer text-center">
                <div class="btn-group">
                    <a href="{% url 'blog:view' object.slug %}" class="btn btn-success" >Просмотреть</a>
                    <a href="{% url 'blog:update' object.slug %}" class="btn btn-warning">Редактировать</a>
                    <a href="{% url 'blog:delete' object.slug %}" class="btn btn-danger">Удалить</a>
                </div>
            </div>
        </div>
        {% endfor %}
        <div class="mb-3 mt-3" style="text-align: center;">
            <a class="p-2 btn btn-primary" href="{% url 'blog:create' %}">Добавить</a>
        </div>
    </div>
</div>
{% endblock %}