blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import ArticleCreateView, ArticleListView, ArticleDetailView, ArticleUpdateView, ArticleDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('create/', ArticleCreateView.as_view(), name='create'),
    path('update/<str:slug>/', ArticleUpdateView.as_view(), name='update'),
    path('delete/<str:slug>/', ArticleDeleteView.as_view(), name='delete'),
    path('', ArticleListView.as_view(), name='list'),
    path('view/<str:slug>/', ArticleDetailView.as_view(), name='view'),
]

catalog/urls.py
from django.urls import path

from catalog.apps import CatalogConfig
from catalog.views import contacts, ProductListView, ProductDetailView, ProductCreateView, ProductUpdateView, \
    manage_versions, ProductDeleteView

app_name = CatalogConfig.name

urlpatterns = [
    path('', ProductListView.as_view(), name='index'),
    path('view/<int:pk>/', ProductDetailView.as_view(), name='product_detail'),
    path('create/', ProductCreateView.as_view(), name='create_product'),
    path('update/<int:pk>', ProductUpdateView.as_view(), name='update_product'),
    path('delete/<int:pk>', ProductDeleteView.as_view(), name='delete_product'),
    path('contacts/', contacts, name='contacts'),
    path('version/update/<int:fk>/', manage_versions, name='update_version'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from catalog import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path

from users.apps import UsersConfig
from users.views import RegisterView, LoginView, LogoutView, ProfileView, verify_view, generate_password_view

app_name = UsersConfig.name

urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('verify/<code>/', verify_view, name='verify'),
    path('generate_password/', generate_password_view, name='generate_password'),
]

users/models.py
from django.apps import apps
from django.contrib.auth.base_user import BaseUserManager
from django.contrib.auth.hashers import make_password
from django.contrib.auth.models import AbstractUser
from django.db import models

from catalog.models import NULLABLE


class UserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        if not email:
            raise ValueError("The given username must be set")
        email = self.normalize_email(email)
        GlobalUserModel = apps.get_model(
            self.model._meta.app_label, self.model._meta.object_name
        )
        email = GlobalUserModel.normalize_username(email)
        user = self.model(email=email, **extra_fields)
        user.password = make_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", False)
        extra_fields.setdefault("is_superuser", False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)

        if extra_fields.get("is_staff") is not True:
            raise ValueError("Superuser must have is_staff=True.")
        if extra_fields.get("is_superuser") is not True:
            raise ValueError("Superuser must have is_superuser=True.")
        return self._create_user(email, password, **extra_fields)


class User(AbstractUser):
    objects = UserManager()
    username = None
    email = models.EmailField(unique=True, verbose_name='Почта (e-mail)')
    avatar = models.ImageField(upload_to='avatars/', verbose_name='Аватар')
    phone_number = models.CharField(max_length=12, verbose_name='Телефон')
    country = models.CharField(max_length=100, verbose_name='Страна')
    verify_code = models.CharField(max_length=10, verbose_name='Код верификации', **NULLABLE)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

users/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django import forms

from users.models import User


class RegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('email', 'first_name', 'last_name', 'avatar', 'phone_number', 'country', 'password1', 'password2')


class ProfileForm(UserChangeForm):
    class Meta:
        model = User
        fields = ('email', 'first_name', 'last_name', 'avatar', 'phone_number', 'country')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['password'].widget = forms.HiddenInput()

users/views.py
import random
import string

from django.conf import settings
from django.contrib.auth.views import LogoutView as BaseLogoutView, LoginView as BaseLoginView
from django.core.mail import send_mail
from django.shortcuts import render, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, UpdateView

from users.forms import RegisterForm, ProfileForm
from users.models import User


class RegisterView(CreateView):
    form_class = RegisterForm
    template_name = 'users/register.html'
    success_url = reverse_lazy('catalog:index')

    def form_valid(self, form):
        user = form.save()
        user.verify_code = ''.join([random.choice(string.digits + string.ascii_letters) for i in range(0, 8)])
        user.is_active = False
        user.save()
        message = (f"Для завершения регистрации на портале ProductStore "
                   f"перейдите по ссылке http://127.0.0.1:8000/users/verify/{user.verify_code}")
        send_mail("Подтверждение регистрации", message, settings.EMAIL_HOST_USER, recipient_list=[user.email])
        return super().form_valid(form)


class ProfileView(UpdateView):
    form_class = ProfileForm
    template_name = 'users/profile.html'
    success_url = reverse_lazy('users:profile')

    def get_object(self, queryset=None):
        return self.request.user


class LoginView(BaseLoginView):
    template_name = 'users/login.html'


class LogoutView(BaseLogoutView):
    pass


def verify_view(request, code):
    user = User.objects.filter(verify_code=code).first()
    if user is None:
        return render(request, 'users/verify_unsuccess.html')
    user.is_active = True
    user.save()
    return render(request, 'users/verify_success.html')


def generate_password_view(request):
    if request.method == 'GET':
        return render(request, 'users/enter_email.html')
    email = request.POST.get('email')
    password = ''.join([random.choice(string.digits + string.ascii_letters) for i in range(0, 8)])
    message = f'Ваш новый пароль: {password}'
    user = User.objects.filter(email=email).first()
    if user is None:
        context = {'email': email}
        return render(request, 'users/generate_password_unsuccess.html', context=context)
    user.set_password(password)
    user.save()
    send_mail("Восстановление пароля на ProductStore", message, settings.EMAIL_HOST_USER,
              recipient_list=[email])
    return render(request, 'users/generate_password_success.html')

users/templates/users/enter_email.html
{% extends 'catalog/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="col-4 offset-4">
<form action="{% url 'users:generate_password' %}" method="post">
    {% csrf_token %}
    <div class="card p-5">
        <label for="ControlInputName" class="form-label">Укажите email</label>
        <input type="email" name="email" required class="form-control" id="ControlInputName" placeholder="email">
        <button class="btn btn-lg btn-primary btn-block mt-2" type="submit">Отправить</button>
    </div>
</form>
</div>
{% endblock %}

users/templates/users/generate_password_success.html
{% extends 'catalog/base.html' %}
{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6 offset-3">
            <div class="card">
                <div class="card-body text-center">
                        <p><b>Новый пароль был отправлен на вашу электронную почту!</b></p>
                        <a href="{% url 'users:login' %}" class="btn btn-primary">Авторизоваться</a>
                        <a href="{% url 'catalog:index' %}" class="btn btn-secondary">На главную</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/generate_password_unsuccess.html
{% extends 'catalog/base.html' %}
{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6 offset-3">
            <div class="card">
                <div class="card-body text-center">
                        <p><b>Пользователь с логином {{ email }} не найден!</b></p>
                        <a href="{% url 'users:generate_password' %}" class="btn btn-primary">Назад</a>
                        <a href="{% url 'catalog:index' %}" class="btn btn-secondary">На главную</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/login.html
{% extends 'catalog/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="col-4 offset-4">
<form class="form-signin" method="post">
    {% csrf_token %}
    <div class="card p-5">
        {% crispy form %}
        <button class="btn btn-lg btn-primary btn-block" type="submit">Войти</button>
    </div>
    <a href="{% url 'users:generate_password' %}">Забыли пароль</a>
</form>
</div>
{% endblock %}

users/templates/users/profile.html
{% extends 'catalog/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="col-6 offset-3">
<form class="form-signup text-left" enctype="multipart/form-data" method="post">
    <div class="card p-5">
        {% crispy form %}
        <button class="btn btn-lg btn-primary btn-block mt-2" type="submit">Сохранить</button>
    </div>
</form>
</div>
{% endblock %}

users/templates/users/register.html
{% extends 'catalog/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="col-6 offset-3">
<form class="form-signup text-left" enctype="multipart/form-data" method="post">
    <div class="card p-5">
        {% crispy form %}
        <button class="btn btn-lg btn-primary btn-block" type="submit">Зарегистрироваться</button>
    </div>
</form>
</div>
{% endblock %}

users/templates/users/verify_success.html
{% extends 'catalog/base.html' %}
{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6 offset-3">
            <div class="card">
                <div class="card-body text-center">
                        <p><b>Вы успешно зарегистрировались на портале!</b></p>
                        <a href="{% url 'users:login' %}" class="btn btn-primary">Авторизоваться</a>
                        <a href="{% url 'catalog:index' %}" class="btn btn-secondary">На главную</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/verify_unsuccess.html
{% extends 'catalog/base.html' %}
{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6 offset-3">
            <div class="card">
                <div class="card-body text-center">
                        <p><b>Неверный код активации!</b></p>
                        <a href="{% url 'catalog:index' %}" class="btn btn-primary">На главную</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}