blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import ArticleCreateView, ArticleListView, ArticleDetailView, ArticleUpdateView, ArticleDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('create/', ArticleCreateView.as_view(), name='create'),
    path('update/<str:slug>/', ArticleUpdateView.as_view(), name='update'),
    path('delete/<str:slug>/', ArticleDeleteView.as_view(), name='delete'),
    path('', ArticleListView.as_view(), name='list'),
    path('view/<str:slug>/', ArticleDetailView.as_view(), name='view'),
]

catalog/urls.py
from django.urls import path

from catalog.apps import CatalogConfig
from catalog.views import contacts, ProductListView, ProductDetailView, ProductCreateView, ProductUpdateView, \
    manage_versions, ProductDeleteView

app_name = CatalogConfig.name

urlpatterns = [
    path('', ProductListView.as_view(), name='index'),
    path('view/<int:pk>/', ProductDetailView.as_view(), name='product_detail'),
    path('create/', ProductCreateView.as_view(), name='create_product'),
    path('update/<int:pk>', ProductUpdateView.as_view(), name='update_product'),
    path('delete/<int:pk>', ProductDeleteView.as_view(), name='delete_product'),
    path('contacts/', contacts, name='contacts'),
    path('version/update/<int:fk>/', manage_versions, name='update_version'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from catalog import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/models.py
from django.db import models
from imagekit.models import ImageSpecField
from pilkit.processors import ResizeToFill

NULLABLE = {'blank': True, 'null': True}


class Product(models.Model):
    name = models.CharField(max_length=150, verbose_name='наименование')
    description = models.TextField(verbose_name='описание', **NULLABLE)
    preview = models.ImageField(upload_to='products/', verbose_name='превью')
    # preview_thumbnail = ImageSpecField(source='preview', processors=[ResizeToFill(300, 300)], format='JPEG')
    category = models.ForeignKey('Category', on_delete=models.CASCADE)
    price = models.IntegerField(verbose_name='цена')
    created_at = models.DateField(verbose_name='дата создания', auto_now_add=True)
    modificated_at = models.DateField(verbose_name='дата изменения', auto_now=True)
    user = models.ForeignKey('users.User', on_delete=models.SET_NULL, verbose_name='Создатель', **NULLABLE)
    is_published = models.BooleanField(default=True, verbose_name="Опубликовано")

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'продукт'
        verbose_name_plural = 'продукты'
        ordering = ['pk']
        permissions = [
            (
                "set_published_status",
                "Can publish product"
            ),
            (
                "change_category",
                "Can change category product"
            ),
            (
                "change_description",
                "Can change description product"
            ),
        ]


class Category(models.Model):
    name = models.CharField(max_length=150, verbose_name='название')
    description = models.TextField(verbose_name='описание')
    created_at = models.DateField(verbose_name='дата создания', auto_now_add=True)

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'категории'


class Version(models.Model):
    product = models.ForeignKey('Product', on_delete=models.CASCADE)
    number = models.IntegerField(verbose_name='номер')
    title = models.CharField(max_length=50, verbose_name='название')
    is_currency = models.BooleanField(verbose_name='текущая', default=False)

    def __str__(self):
        return f'{self.title} {self.number}'

    class Meta:
        verbose_name = 'версия'
        verbose_name_plural = 'версии'

catalog/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.forms import ModelForm, BaseInlineFormSet, BaseModelFormSet, CheckboxInput

from catalog.models import Product, Version


class ProductForm(ModelForm):
    class Meta:
        model = Product
        exclude = ('created_at', 'modificated_at', 'user')

    def __init__(self, *args, **kwargs):
        request = kwargs.pop('request', None)
        user_id = kwargs.pop('user', None)

        super().__init__(*args, **kwargs)

        for field_name, field in self.fields.items():
            if type(field.widget) != CheckboxInput:
                field.widget.attrs['class'] = 'form-control'
            else:
                field.widget.attrs['class'] = 'form-check-input'
        custom_perms: tuple = (
            'catalog.set_published_status',
            'catalog.change_category',
            'catalog.change_description',
        )
        if request is not None:
            auth_user = request.user
            if auth_user != user_id and not auth_user.is_superuser:
                self.fields['name'].disabled = True
                self.fields['preview'].disabled = True
                self.fields['price'].disabled = True
            if not auth_user.has_perm('catalog.set_published_status'):
                self.fields['is_published'].disabled = True
        else:
            self.fields.pop('is_published')

    def clean_name(self):
        cleaned_data = self.cleaned_data.get('name')
        restricted_words = ['казино', 'криптовалюта', 'крипта', 'биржа',
                            'дешево', 'бесплатно', 'обман', 'полиция', 'радар']

        for word in restricted_words:
            if word.lower() in cleaned_data:
                raise forms.ValidationError('Недопустимое имя продукта')
        return cleaned_data


class VersionForm(ModelForm):
    class Meta:
        model = Version
        fields = '__all__'
        widgets = {'product': forms.HiddenInput()}


class VersionFormSet(BaseModelFormSet):

    def clean(self):
        is_currency = False
        for form in self.forms:
            if form.cleaned_data.get('is_currency'):
                if is_currency:
                    raise ValidationError("только одна версия может быть текущей")
                else:
                    is_currency = True


class VersionInlineFormSet(BaseInlineFormSet):

    def clean(self):
        is_currency = False
        for form in self.forms:
            if form.cleaned_data.get('is_currency'):
                if is_currency:
                    raise ValidationError("только одна версия может быть текущей")
                else:
                    is_currency = True

catalog/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.forms import modelformset_factory, inlineformset_factory
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, DetailView, CreateView, UpdateView, FormView, DeleteView

from catalog.forms import ProductForm, VersionForm, VersionInlineFormSet, VersionFormSet
from catalog.models import Product, Version


class ProductListView(ListView):
    model = Product
    paginate_by = 4
    template_name = "catalog/home.html"

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        if not self.request.user.is_authenticated:
            queryset = queryset.filter(is_published=True)
        elif not self.request.user.groups.filter(name="moderator").exists():
            queryset = queryset.filter(user=self.request.user)
        for product in queryset:
            version = product.version_set.all().filter(is_currency=True).first()
            product.version = version
        return queryset


class ProductDetailView(DetailView):
    model = Product
    template_name = "catalog/products.html"
    login_url = reverse_lazy('users:login')


class ProductCreateView(LoginRequiredMixin, CreateView):
    model = Product
    form_class = ProductForm
    exclude = ('created_at', 'modificated_at',)
    success_url = reverse_lazy('catalog:index')
    login_url = reverse_lazy('users:login')

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        version_formset = inlineformset_factory(parent_model=Product, model=Version, form=VersionForm,
                                                formset=VersionInlineFormSet, extra=1, can_delete=True)
        if self.request.method == 'POST':
            context_data['formset'] = version_formset(self.request.POST, instance=self.object)
        else:
            context_data['formset'] = version_formset(instance=self.object)
        return context_data

    def form_valid(self, form):
        formset = self.get_context_data()['formset']
        if formset.is_valid():
            self.object = form.save()
            self.object.user = self.request.user
            formset.instance = self.object
            formset.save()
            return super().form_valid(form)
        else:
            return super().form_invalid(form)


class ProductUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Product
    form_class = ProductForm
    exclude = ('created_at', 'modificated_at',)
    success_url = reverse_lazy('catalog:index')
    login_url = reverse_lazy('users:login')

    def test_func(self):
        custom_perms: tuple = (
            'catalog.set_published_status',
            'catalog.change_category',
            'catalog.change_description',
        )
        return self.request.user == self.get_object().user or self.request.user.has_perms(custom_perms)

    def handle_no_permission(self):
        return render(request=self.request, template_name='catalog/no_permissions.html')

    def get_form_kwargs(self, *args, **kwargs):
        form_kwargs = super().get_form_kwargs(*args, **kwargs)
        form_kwargs['request'] = self.request
        form_kwargs['user'] = self.object.user
        return form_kwargs

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        if self.request.user != self.get_object().user:
            return context_data
        version_formset = inlineformset_factory(parent_model=Product, model=Version, form=VersionForm,
                                                formset=VersionInlineFormSet, extra=1, can_delete=True)
        if self.request.method == 'POST':
            context_data['formset'] = version_formset(self.request.POST, instance=self.object)
        else:
            context_data['formset'] = version_formset(instance=self.object)
        return context_data

    def form_valid(self, form):
        formset = self.get_context_data()['formset']
        if formset.is_valid():
            formset.instance = self.object
            formset.save()
            return super().form_valid(form)
        else:
            return super().form_invalid(form)


class ProductDeleteView(LoginRequiredMixin, DeleteView):
    model = Product
    success_url = reverse_lazy('catalog:index')
    login_url = reverse_lazy('users:login')


def contacts(request):
    return render(request, 'catalog/contacts.html')


@login_required
def manage_versions(request, fk):
    version_formset = modelformset_factory(Version, form=VersionForm, formset=VersionFormSet, extra=1, can_delete=True)
    if request.method == 'POST':
        formset = version_formset(request.POST)
        formset.extra_forms[0].fields['product'].initial = fk
        if formset.is_valid():
            formset.save()
            return redirect(reverse('catalog:index'))
    else:
        formset = version_formset(
            queryset=Version.objects.all().filter(product=fk))
        formset.extra_forms[0].fields['product'].initial = fk
    return render(request, "catalog/version_form.html", {'formset': formset})


class VersionUpdateView(LoginRequiredMixin, FormView):
    model = Version
    form_class = VersionForm
    template_name = "catalog/version_form.html"
    success_url = reverse_lazy('catalog:index')
    login_url = reverse_lazy('users:login')

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        version_formset = modelformset_factory(Version, form=VersionForm, formset=VersionFormSet, extra=1,
                                               can_delete=True)
        if self.request.method == 'POST':
            formset = version_formset(self.request.POST)
            formset.extra_forms[0].fields['product'].initial = self.kwargs.get('fk')
            if formset.is_valid():
                formset.save()
        else:
            formset = version_formset(
                queryset=Version.objects.all().filter(product=self.kwargs.get('fk')))
            formset.extra_forms[0].fields['product'].initial = self.kwargs.get('fk')
        return {'formset': formset}

    def form_valid(self, form):
        return HttpResponseRedirect(self.get_success_url())

    def post(self, request, *args, **kwargs):

        super().post(self, request, *args, **kwargs)
        form = self.get_form()
        print(form.is_valid())

        version_formset = modelformset_factory(Version, form=VersionForm, formset=VersionFormSet, extra=1,
                                               can_delete=True)
        formset = version_formset(self.request.POST)
        formset.extra_forms[0].fields['product'].initial = self.kwargs.get('fk')

        if formset.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

catalog/templates/catalog/add_product.html
{% extends 'catalog/base.html' %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Добавление продукта</h1>
</div>
<form method="post" action="{% url 'catalog:product_list' %}" enctype="multipart/form-data" class="form-floating">
    {% csrf_token %}
    <div class="w-50">
        <div class="mb-3">
            <label for="ControlInputName" class="form-label">Название продукта</label>
            <input type="text" name="name" class="form-control" id="ControlInputName" placeholder="Название">
        </div>
        <div class="mb-3">
            <label for="exampleFormControlTextarea1" class="form-label">Описание</label>
            <textarea class="form-control" id="exampleFormControlTextarea1" rows="3" name="description"></textarea>
        </div>
        <div class="mb-3">
            <label for="ControlInputCategory" class="form-label">Категория</label>
            <select class="form-select" aria-label="Выберите категорию" id="ControlInputCategory" name="category">
                {% for object in object_list %}
                <option value="{{object.id}}">{{object.name}}</option>
                {% endfor %}
            </select>
        </div>
        <div class="mb-3">
            <label for="ControlInputPrice" class="form-label">Цена</label>
            <input type="text" class="form-control" id="ControlInputPrice" placeholder="цена" name="price">
        </div>
        <div class="mb-3">
            <label for="ControlInputFile" class="form-label">Изображение</label>
            <input class="form-control" type="file" id="ControlInputFile" name="preview">
        </div>
    </div>
    <div class="mb-3">
        <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
    </div>
</form>
{% endblock %}

catalog/templates/catalog/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ title }}</title>
    <link href="{% static 'css/bootstrap.min.css'%}" rel="stylesheet">
    <style>
    ul.errorlist {

  font-weight: bold;
  color: red;
}
    </style>
</head>
<body>
{% include 'catalog/includes/inc_main_menu.html' %}
<div class="container">

{% block content %}
{% endblock %}

<footer class="pt-4 my-md-5 pt-md-5 border-top">
    <div class="row">
        <div class="col-12 col-md">
            {{ title }}
            <small class="d-block mb-3 text-muted">&copy; {% now 'Y' %}</small>
        </div>
        <div class="col-6 col-md">
            <h5>Категории</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="#">Рассылки</a></li>
                <li><a class="text-muted" href="#">Телеграм боты</a></li>
                <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                <li><a class="text-muted" href="#">Веб-приложения</a></li>
                <li><a class="text-muted" href="#">Микросервисы</a></li>
            </ul>
        </div>
        <div class="col-6 col-md">
            <h5>Дополнительно</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="#">Мы пишем</a></li>
            </ul>
        </div>
        <div class="col-6 col-md">
            <h5>О нас</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="{% url 'catalog:contacts' %}">Контакты</a></li>
            </ul>
        </div>
    </div>
</footer>
</div>
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

catalog/templates/catalog/contacts.html
{% extends 'catalog/base.html' %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Контакты</h1>
</div>
<div class="row text-start">
    <div class="col-lg-9 col-md-6 col-sm-12">
        <div class="card mb-4 box-shadow">
            <div class="card-body">
                <table class="table table-striped">
                    <tr>
                        <td class="w-25">Страна</td>
                        <td>USA</td>
                    </tr>
                    <tr>
                        <td class="w-25">ИНН</td>
                        <td>91-1144442</td>
                    </tr>
                    <tr>
                        <td class="w-25">Адрес</td>
                        <td>Redmond,WA,98052-6399</td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
    <div class="col-lg-3 col-md-6 col-sm-12">
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
            </div>
            <div class="card-body">
                <form method="post" action="/" class="form-floating">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="name">Имя</label>
                        <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя" required>
                    </div>
                    <div class="mb-3">
                        <label for="phone">Телефон</label>
                        <input type="text" name="phone" class="form-control" id="phone" placeholder="Контактный телефон"
                               required>
                    </div>
                    <div class="mb-3">
                        <label for="message">Сообщение</label>
                        <textarea type="text" name="message" class="form-control" id="message"
                                  placeholder="Введите сообщение..." required></textarea>
                    </div>
                    <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/home.html
{% extends 'catalog/base.html' %}
{% load mediapath %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Productstore</h1>
    <p class="lead">Магазин продуктовых товаров</p>
</div>

<div class="row text-center">
    {% for object in object_list %}
    <div class="col-3">
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal">
                    <a href="/view/{{object.id}}">{{object|truncatechars:100}}</a></h4>
                    <h6 class="mt-3">
                        {% if object.version %}
                            Версия:
                            {% if object.user == user %}
                            <a href="{% url 'catalog:update_version' object.pk %}">{{object.version}}</a>
                            {% else %}
                                {{object.version}}
                            {% endif %}
                        {% else %}
                            Версия:
                            {% if object.user == user %}
                            <a href="{% url 'catalog:update_version' object.pk %}">не определена</a>
                            {% else %}
                                не определена
                            {% endif %}
                        {% endif %}
                    </h6>
            </div>
            <div class="card-body">
                <h1 class="card-title pricing-card-title">{{object.price}} руб.</h1>
                <div class="list-unstyled mt-3 mb-4 text-start m-3">
                    <!--<img class="card-img" src="{{object.preview.url}}">-->
                    <!--<img class="card-img" src="{% mediapath object.preview %}">-->
                    <img class="card-img img-thumbnail mw-100 mh-100"  src="{{ object.preview|mediapath_filter }}">
                    <!--<img class="card-img img-thumbnail mw-100 mh-100"  src="{{ object.preview_thumbnail.url }}">-->
                </div>
                <button type="button" class="btn btn-lg btn-block btn-outline-primary">Купить</button>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% if user.is_authenticated %}
<div class="mb-3" style="text-align: center;">
    <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:create_product' %}">Добавить продукт</a>
</div>
{% endif %}

{% if is_paginated %}
<nav aria-label="Page navigation example">
    <ul class="pagination">
        {% if page_obj.has_previous %}
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a></li>
        {% else %}
            <li class="page-item"><a class="page-link btn disabled" href="#">Previous</a></li>
        {% endif %}
         {% for pn in page_obj.paginator.page_range %}
                <li>
                    <a class="page-link" href="{% url 'catalog:index' %}?page={{ pn }}">{{ pn }}</a>
                </li>
        {% endfor %}
        {% if page_obj.has_next %}
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a></li>
        {% else %}
            <li class="page-item"><a class="page-link btn disabled" href="#">Next</a></li>
        {% endif %}
    </ul>
</nav>
{% endif %}
{% endblock %}

catalog/templates/catalog/no_permissions.html
{% extends 'catalog/base.html' %}
{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6 offset-3">
            <div class="card">
                <div class="card-body text-center">
                        <p><b>У вас недостаточно прав для выполнения данной операции!</b></p>
                        <a href="{% url 'catalog:index' %}" class="btn btn-primary">На главную</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/product_confirm_delete.html
{% extends 'catalog/base.html' %}
{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6 offset-3">
            <div class="card">
                <div class="card-body text-center">
                    <form method="post">
                        {% csrf_token %}
                        <p><b>Хотите удалить продукт <q>{{object.name}}</q>?</b></p>
                        <button type="submit" class="btn btn-danger">Удалить</button>
                        <a href="{% url 'catalog:index' %}" class="btn btn-warning">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/product_form.html
{% extends 'catalog/base.html' %}
{% block content %}
<div class="col-12">
    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        {% if not object %}
        <h1 class="display-4">Добавление продукта</h1>
        {% else %}
        <h1 class="display-4">Редактирование продукта</h1>
        {% endif %}
    </div>

    <div class="row">
        <div class="col-12">
            <form class="row" method="post" enctype="multipart/form-data">
                <div class="col-6">
                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title text-center">Продукт</h3>
                        </div>
                        <div class="card-body">
                            {% csrf_token %}
                            {{form.as_p}}
                        </div>
                    </div>
                </div>

                <div class="col-6">
                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title text-center">Версии продукта</h3>
                        </div>
                        <div class="card-body">
                            {{ formset.management_form }}
                            {{ formset.non_form_errors }}
                            {% for form in formset %}
                            {{ form.as_p }}
                            {% endfor %}
                        </div>

                    </div>
                </div>

                <div class="m-3 text-center">
                    <button type="submit" class="btn btn-lg btn-block btn-outline-primary">
                        {% if object %}
                        Сохранить
                        {% else %}
                        Добавить
                        {% endif %}
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/products.html
{% extends 'catalog/base.html' %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-5">{{ object.name }}</h1>
</div>
<p class="text-start"><b>Описание:</b> {{ object.description }}</p>
<p class="text-start"><b>Категория:</b> {{ object.category }}</p>
<p class="text-start"><b>Цена:</b> {{ object.price }} руб.</p>
<p class="text-start"><b>Дата добавления:</b> {{ object.created_at }}</p>
<p class="text-start"><b>Дата изменения:</b> {{ object.modificated_at }}</p>
<p class="text-start"><b>Добавил:</b> {{ object.user|default:'-' }}</p>
{% if user.is_authenticated %}
<div class="mb-3" style="text-align: center;">
    <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:update_product' object.pk %}">Редактировать</a>
    <a class="p-2 btn btn-outline-danger" href="{% url 'catalog:delete_product' object.pk %}">удалить</a>
</div>
{% endif %}
{% endblock %}

catalog/templates/catalog/version_form.html
{% extends 'catalog/base.html' %}
{% block content %}
<div class="col-12">
    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h1 class="display-4">Редактирование версий</h1>
    </div>
    <div class="row">
        <div class="w-50 mx-auto">
            <form action="" method="post" class="form-floating">
                {% csrf_token %}
                {{ formset.management_form }} <!-- Important: this is required to manage the forms in the formset -->
                {{ formset.non_form_errors }}
                {% for form in formset %}
                {{ form.as_p }}
                {% endfor %}
                <div class="mb-3 text-center">
                    <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Сохранить</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}